# Generated by Django 4.2.9 on 2026-03-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_can_manage_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_id',
            field=models.IntegerField(default=1),
        ),
    ]
