# Generated by Django 4.2.7 on 2026-03-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('bike', 'Vélo'), ('accessory', 'Accessoire'), ('part', 'Pièce détachée'), ('prestation', 'Prestation'), ('occasion', 'Occasion')], default='bike', max_length=20),
        ),
    ]
