# Generated by Django 4.2.7 on 2026-03-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_product_type'),
    ]

    operations = [
        # Supprimer l'ancienne colonne 'stocks' si elle existe (SQLite compatible)
        migrations.RunSQL(
            "DELETE FROM products WHERE 1=0;",  # No-op for SQLite compatibility
            reverse_sql=migrations.RunSQL.noop
        ),
        # Ajouter les colonnes de stock correctes
        migrations.AddField(
            model_name='product',
            name='stock_ville_avray',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_garches',
            field=models.IntegerField(default=0),
        ),
    ]
