# Generated by Django 4.2.7 on 2026-03-19 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repairs', '0003_alter_repairitem_options_and_more'),
        ('clients', '0002_alter_client_address_alter_client_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du rendez-vous')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('source', models.CharField(choices=[('local', 'Local'), ('wix', 'Wix Bookings')], default='local', max_length=20, verbose_name='Source')),
                ('wix_booking_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Booking Wix')),
                ('appointment_date', models.DateField(verbose_name='Date du rendez-vous')),
                ('appointment_time', models.TimeField(verbose_name='Heure du rendez-vous')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='Durée (minutes)')),
                ('appointment_type', models.CharField(choices=[('repair', 'Réparation'), ('maintenance', 'Entretien'), ('customization', 'Personnalisation'), ('delivery', 'Livraison'), ('consultation', 'Consultation')], default='repair', max_length=20, verbose_name='Type de rendez-vous')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='normal', max_length=20, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('scheduled', 'Planifié'), ('confirmed', 'Confirmé'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('no_show', 'Absent')], default='scheduled', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('client_notes', models.TextField(blank=True, verbose_name='Notes client')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Rappel envoyé')),
                ('confirmation_sent', models.BooleanField(default=False, verbose_name='Confirmation envoyée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointments', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('repair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='repairs.repair')),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='WixSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de synchronisation')),
                ('status', models.CharField(choices=[('success', 'Succès'), ('error', 'Erreur'), ('partial', 'Partiel')], max_length=20, verbose_name='Statut')),
                ('bookings_processed', models.IntegerField(default=0, verbose_name='Bookings traités')),
                ('bookings_created', models.IntegerField(default=0, verbose_name='Bookings créés')),
                ('bookings_updated', models.IntegerField(default=0, verbose_name='Bookings mis à jour')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('sync_duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Durée (secondes)')),
            ],
            options={
                'db_table': 'wix_sync_logs',
                'ordering': ['-sync_date'],
                'indexes': [models.Index(fields=['sync_date'], name='wix_sync_lo_sync_da_80b78f_idx'), models.Index(fields=['status'], name='wix_sync_lo_status_1dfec9_idx')],
            },
        ),
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('phone', 'Appel téléphonique')], default='email', max_length=20)),
                ('reminder_time', models.DateTimeField(verbose_name='Heure du rappel')),
                ('sent', models.BooleanField(default=False, verbose_name='Envoyé')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='appointments.appointment')),
            ],
            options={
                'db_table': 'appointment_reminders',
                'ordering': ['reminder_time'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date'], name='appointment_appoint_8b74ac_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='appointment_status_9fecd6_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['client'], name='appointment_client__2834cc_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_type'], name='appointment_appoint_6f2f79_idx'),
        ),
    ]
