# Generated by Django 4.2.9 on 2026-03-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='source',
            field=models.CharField(choices=[('local', 'Local'), ('wix', 'Wix Bookings')], default='local', max_length=20, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='wix_booking_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Booking Wix'),
        ),
        migrations.CreateModel(
            name='WixSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de synchronisation')),
                ('status', models.CharField(choices=[('success', 'Succès'), ('error', 'Erreur'), ('partial', 'Partiel')], max_length=20, verbose_name='Statut')),
                ('bookings_processed', models.IntegerField(default=0, verbose_name='Bookings traités')),
                ('bookings_created', models.IntegerField(default=0, verbose_name='Bookings créés')),
                ('bookings_updated', models.IntegerField(default=0, verbose_name='Bookings mis à jour')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('sync_duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Durée (secondes)')),
            ],
            options={
                'db_table': 'wix_sync_logs',
                'ordering': ['-sync_date'],
                'indexes': [models.Index(fields=['sync_date'], name='wix_sync_lo_sync_da_80b78f_idx'), models.Index(fields=['status'], name='wix_sync_lo_status_1dfec9_idx')],
            },
        ),
    ]
