# Generated by Django 4.2.7 on 2026-03-19 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_fix_stock_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_alter_client_address_alter_client_city_and_more'),
        ('orders', '0004_orderitem_description_alter_orderitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('store', models.CharField(choices=[('ville_avray', "Ville d'Avray"), ('garches', 'Garches')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('accepted', 'Accepté'), ('rejected', 'Refusé'), ('expired', 'Expiré'), ('converted', 'Converti en commande')], default='draft', max_length=20)),
                ('quote_date', models.DateField(auto_now_add=True)),
                ('valid_until', models.DateField(verbose_name="Valide jusqu'au")),
                ('subtotal_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('quote_pdf', models.FileField(blank=True, null=True, upload_to='quotes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='clients.client')),
                ('converted_to_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quote', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tva_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subtotal_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quote')),
            ],
            options={
                'db_table': 'quote_items',
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['quote_number'], name='quotes_quote_n_a300f2_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status'], name='quotes_status_b396a9_idx'),
        ),
    ]
