# Generated by Django 4.2.9 on 2026-03-17 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_fix_stock_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('yearly', 'Annuel')], max_length=20)),
                ('date', models.DateField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_clients', models.IntegerField(default=0)),
                ('total_clients', models.IntegerField(default=0)),
                ('returning_clients', models.IntegerField(default=0)),
                ('total_products', models.IntegerField(default=0)),
                ('low_stock_products', models.IntegerField(default=0)),
                ('out_of_stock_products', models.IntegerField(default=0)),
                ('total_repairs', models.IntegerField(default=0)),
                ('completed_repairs', models.IntegerField(default=0)),
                ('average_repair_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_quotes', models.IntegerField(default=0)),
                ('pending_quotes', models.IntegerField(default=0)),
                ('accepted_quotes', models.IntegerField(default=0)),
                ('rejected_quotes', models.IntegerField(default=0)),
                ('total_appointments', models.IntegerField(default=0)),
                ('completed_appointments', models.IntegerField(default=0)),
                ('cancelled_appointments', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dashboard_stats',
                'indexes': [models.Index(fields=['period', 'date'], name='dashboard_s_period_72e75d_idx'), models.Index(fields=['year', 'month'], name='dashboard_s_year_bc6d4c_idx'), models.Index(fields=['year', 'week'], name='dashboard_s_year_653584_idx')],
                'unique_together': {('period', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('yearly', 'Annuel')], max_length=20)),
                ('rank', models.IntegerField()),
                ('date', models.DateField()),
                ('total_sales', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('market_share', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_rankings', to='products.product')),
            ],
            options={
                'db_table': 'top_products',
                'indexes': [models.Index(fields=['period', 'date', 'rank'], name='top_product_period_163931_idx'), models.Index(fields=['product'], name='top_product_product_2c3e2a_idx')],
                'unique_together': {('period', 'date', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='ProductSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('quantity_sold', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_start', models.IntegerField(default=0)),
                ('stock_end', models.IntegerField(default=0)),
                ('stock_received', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_stats', to='products.product')),
            ],
            options={
                'db_table': 'product_sales',
                'indexes': [models.Index(fields=['product', 'date'], name='product_sal_product_97b5d4_idx'), models.Index(fields=['year', 'month'], name='product_sal_year_3ec4d0_idx'), models.Index(fields=['quantity_sold'], name='product_sal_quantit_44fdb7_idx')],
                'unique_together': {('product', 'year', 'month')},
            },
        ),
    ]
