# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=50, verbose_name='Type de test')),
                ('test_name', models.CharField(max_length=100, verbose_name='Nom du test')),
                ('status', models.CharField(max_length=20, choices=[('success', 'Succès'), ('error', 'Erreur'), ('warning', 'Avertissement')], verbose_name='Statut')),
                ('message', models.TextField(verbose_name='Message')),
                ('details', models.JSONField(default=dict, blank=True, verbose_name='Détails')),
                ('execution_time', models.FloatField(help_text='Temps d\'exécution en secondes', verbose_name='Temps d\'exécution')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Log de test',
                'verbose_name_plural': 'Logs de tests',
                'ordering': ['-created_at'],
                'db_table': 'test_module_testlog',
            },
        ),
        migrations.CreateModel(
            name='testdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('data', models.JSONField(default=dict, blank=True, verbose_name='Données')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Donnée de test',
                'verbose_name_plural': 'Données de test',
                'ordering': ['-created_at'],
                'db_table': 'test_module_testdata',
            },
        ),
    ]
