# Generated by Django 4.2.7 on 2026-03-16 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_notes'),
        ('invoices', '0002_rename_pdf_file_invoice_invoice_pdf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date'], 'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='paid_at',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(auto_now_add=True, verbose_name='Date de facture'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='Payée'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order'),
        ),
    ]
